CREATE TABLE Books(
  "subtitle" varchar(50),
  "weight" varchar(15),
  "covers" int,
  "latest_revision" int,
  "edition_name" varchar(50),
  "title" varchar(50),
  "languages_key" varchar(15),
  "subjects" varchar(100),
  "physical_dimensions" varchar(30),
  "revision" int,
  "publishers" varchar(50),
  "physical_format" varchar(15),
  "last_modified_value" DATETIME,
  "key" varchar(15) NOT NULL PRIMARY KEY,
  "created_value" DATETIME,
  "identifiers_librarything" INT,
  "identifiers_goodreads" varchar(50),
  "isbn_13" varchar(13),
  "isbn_10" varchar(10),
  "publish_date" varchar(9),
  "ocaid" varchar(50),
  "first_sentence_value" varchar(150),
  "source_records" varchar(50),
  "ia_box_id" varchar(8),
  "number_of_pages" int,
  "oclc_numbers" int,
  "lc_classifications" varchar(20),
  "publish_country" varchar(3),
  "by_statement" varchar(20),
  "publish_places" varchar(50),
  'pagination' varchar(20),
  "local_id" varchar(30),
  "contributions" varchar(100),
  "dewey_decimal_class" varchar(20),
  "lccn" int,
  "work_title" varchar(50),
  "url" varchar(50),
  "series" varchar(50),
  "description_value" varchar(50),
  "full_title" varchar(50),
  "table_of_contents_title" varchar(50),
  "id" int,
  "genres" varchar(50),
  'identifiers_amazon' varchar(50),
  "table_of_contents_level" varchar(10),
  "table_of_contents_label" varchar(10),
  "table_of_contents_pagenum" varchar(10),
  "ia_loaded_id" varchar(20),
  "subject_place" varchar(20),
  'identifiers_overdrive' varchar(50),
  "uri_descriptions" varchar(50),
  "uris" varchar(30),
  "work_titles" varchar(50),
  "subject_time" varchar(30),
  "contributors_role" varchar(50),
  "contributors_name" varchar(50),
  "other_titles" varchar(50),
  "oclc_number" varchar(20),
  "translated_from_key" varchar(50),
  "translation_of" varchar(50),
  "notes" varchar(50),
  "location" varchar(50),
  "description" varchar(250),
  "links_url" varchar(50),
  "links_title" varchar(50),
  "copyright_date" DATETIME
);

Create Table authors(
  "name" varchar(50),
  "personal_name" varchar(50),
  "last_modified_value" DATETIME,
  "key" varchar(15) NOT NULL PRIMARY KEY,
  "id" int,
  "revision" int,
  "bio_value" varchar(50),
  "links_url" varchar(50),
  "links_type_key" varchar(50),
  "links_title" varchar(50),
  "created_value" DATETIME,
  "photos" varchar(50),
  "latest_revision" int,
  "birth_date" DATE,
  "remote_ids_viaf" varchar(15),
  "remote_ids_wikidata" varchar(15),
  "remote_ids_isni" varchar(15),
  "death_date" DATE,
  "alternate_names" varchar(50),
  "wikipedia" varchar(50),
  "title" varchar(50),
  "location" varchar(50),
  "entity_type" varchar(20),
  "role" varchar(5),
  "fuller_name" varchar(50),
  "bio" varchar(250)
);

Create Table bridge(
  "author_key" varchar(15),
  "book_key" varchar(15)
)
